# Generated by Django 5.2 on 2025-04-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksandauthorsapp', '0002_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='last_namre',
            new_name='last_name',
        ),
    ]
