# Generated by Django 5.2 on 2025-04-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksandauthorsapp', '0003_rename_last_namre_author_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='booksandauthorsapp.book'),
        ),
    ]
